spring:
  main:
    allow-circular-references: true

telegram:
  component-package: "io.github.dmitriyutkin.tgbotstarter"
  default-comps:
    create: false
    exclude-commands: "/now,/echo"

  bot:
    token: "7081112351:AAHrC8txMbe2N32TLFDqVsVHTe7Z1tw5qz8"
    username: "hh_helper_robot"
    greetings: "Welcome to telegram bot framework, enjoy!"
    state:
      redis:
        enabled: false
        ttl-in-min: ${REDIS_STATE_TTL:5}
